name: Robot Framework Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgtk-3-dev libasound2-dev
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify files
      run: |
        echo "Estrutura de arquivos:"
        ls -la
        echo "Conteúdo do webServerApiSettings.json:"
        cat webServerApiSettings.json
        
    - name: Start virtual display
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo "DISPLAY=:99" >> $GITHUB_ENV
        
    - name: Get server port
      id: port
      run: |
        # Comando robusto com tratamento de erro
        PORT=$(python -c "import json; try: print(json.load(open('webServerApiSettings.json', 'r'))['webServerPort'] except: print(8080)")
        echo "PORT=$PORT" >> $GITHUB_ENV
        echo "Porta do servidor: $PORT"
        
    - name: Start Flask app
      run: |
        nohup python app.py > flask.log 2>&1 &
        sleep 5
        echo "Flask rodando na porta ${{ env.PORT }}"
        cat flask.log
        
    - name: Run Robot tests
      run: |
        # Força a geração dos relatórios no diretório atual
        robot -d ./ -v PORT:${{ env.PORT }} tests/login_tests.robot
        
    - name: List generated files
      run: |
        echo "Arquivos gerados:"
        ls -la
        echo "Verificando relatórios:"
        [ -f "report.html" ] && echo "report.html encontrado" || echo "report.html NÃO encontrado"
        [ -f "log.html" ] && echo "log.html encontrado" || echo "log.html NÃO encontrado"
        [ -f "output.xml" ] && echo "output.xml encontrado" || echo "output.xml NÃO encontrado"
        
    - name: Upload reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: robot-reports
        path: |
          ./report.html
          ./log.html
          ./output.xml