name: Robot Framework Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Chrome browser
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        # Instala a versão compatível com o Chrome instalado
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
        CHROME_MAJOR_VERSION=${CHROME_VERSION%.*.*}
        wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR_VERSION
        CHROMEDRIVER_VERSION=$(cat LATEST_RELEASE_$CHROME_MAJOR_VERSION)
        wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        chromedriver --version

    - name: Install system dependencies
      run: |
        sudo apt-get install -y xvfb libgtk-3-dev libasound2-dev
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        
  
    - name: Start services
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        nohup python app.py > flask.log 2>&1 &
        sleep 5
        
    - name: Run tests
      run: |
        robot -d ./ -v PORT:${{ env.PORT }} tests/login_tests.robot
        
    - name: Upload reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: robot-reports
        path: |
          ./report.html
          ./log.html
          ./output.xml