name: Robot Framework Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y xvfb libgtk-3-dev libasound2-dev
        
    - name: Start virtual display (for headless testing)
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo "DISPLAY=:99" >> $GITHUB_ENV
        
    - name: Start Flask app
      run: |
        nohup python app.py > flask.log 2>&1 &
        sleep 5  # Wait for app to start
        cat flask.log
        
    - name: Run Robot tests
      run: robot tests/login_tests.robot
      
    - name: Upload reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: robot-reports
        path: |
          report.html
          log.html
          output.xml
