name: Robot Framework Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Validate JSON
      run: |
        if [ -f "webServerApiSettings.json" ]; then
            python -m json.tool webServerApiSettings.json > /dev/null || (echo "JSON inválido!"; exit 1)
        else
            echo "Usando porta padrão 8080 (arquivo não encontrado)"
            echo "PORT=8080" >> $GITHUB_ENV
        fi

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgtk-3-dev libasound2-dev
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Get server port
      if: ${{ !env.PORT }}
      run: |
        PORT=$(python -c "import json; \
        try: \
            with open('webServerApiSettings.json', 'r') as f: \
                print(json.load(f)['webServerPort']) \
        except: \
            print(8080)")
        echo "PORT=$PORT" >> $GITHUB_ENV
        echo "Porta do servidor: $PORT"
        
    - name: Start services
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        nohup python app.py > flask.log 2>&1 &
        sleep 5
        
    - name: Run tests
      run: |
        robot -d ./ -v PORT:${{ env.PORT }} tests/login_tests.robot
        
    - name: Upload reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: robot-reports
        path: |
          ./report.html
          ./log.html
          ./output.xml
        retention-days: 3