name: Robot Framework Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgtk-3-dev libasound2-dev
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify files
      run: |
        ls -la
        cat requirements.txt
        cat webServerApiSettings.json
        
    - name: Start virtual display
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo "DISPLAY=:99" >> $GITHUB_ENV
        
    - name: Start Flask app
      run: |
        # Usa a porta do webServerApiSettings.json
        PORT=$(python -c "import json; print(json.load(open('webServerApiSettings.json'))['webServerPort']")
        nohup python app.py > flask.log 2>&1 &
        sleep 5
        echo "Flask rodando na porta $PORT"
        cat flask.log
        
    - name: Run Robot tests
      run: |
        # Obtém a porta dinamicamente
        PORT=$(python -c "import json; print(json.load(open('webServerApiSettings.json'))['webServerPort']")
        robot -v PORT:$PORT tests/login_tests.robot
      
    - name: Upload reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: robot-reports
        path: |
          report.html
          log.html
          output.xml